title: ./0b3log
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: ""
    values:
      layout: default

callouts:
  note:
    title: Note
    color: blue
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow
  tip:
    title: Tip
    color: green

color_scheme: bluetopaz
